### ISSUE TITLE
Email template design gets break after implement patch APSB22-48

### ISSUE THREAD

**Issue by digitaldeve** [EmicoEcommerce/Magento-APSB22-48-Security-Patches#13]
We are facing the issue in the email template as well as in CMS pages where the "getCmsFilterContent" function is used in code files to parse the content WYSIWYG editor content after implementing the patch APSB22-48 Security Patches.

Email templates not parsing the {{inlinecss file="css/email-inline.css"}} file and email design get broken in actual received email copy.

Please provide some solution to fix this issue.

**Comment by stijnbernards** [comment]
Hi @digitaldeve ,

The patch makes changes in the Magento 2 template processor which breaks nested template parsing.
Is the email you're sending perhaps sent via custom code? and Might it be that the entire email is wrapped in the Magento 2 translation function(`__()`).

**Comment by digitaldeve** [comment]
No there is no customization implemented in the email template from our side. Also, we checked with Default Magento 2.3.7-p2 by applying the patch APSB22-48 and the email template design get broken after implementing the patch. Please check the attached screenshot for the same.

![email-preview-template](https://user-images.githubusercontent.com/117343606/200760620-31455fc8-7f10-42ff-8166-11c86d43589c.png)
