### ISSUE TITLE
Magento v2.4.3(-p[123])? also affected?

### ISSUE THREAD

**Issue by tim-breitenstein-it** [EmicoEcommerce/Magento-APSB22-48-Security-Patches#3]
Hey,

du you know if Magento v2.4.3(-p[123])? is also affected and need to be patched?

**Comment by poespas** [comment]
It is effected, there is a full-on patch available from Magento's side, but we ( @mooore-digital ) will be working on implementing patches for these soon too!

**Comment by tim-breitenstein-it** [comment]
Can you refer the Magento official patch?

Only found this: https://helpx.adobe.com/security/products/magento/apsb22-48.html

**Comment by stijnbernards** [comment]
@tim-breitenstein-it Those are the official patches but they're only available for Magento 2.4.5 and Magento 2.4.4. That's why we're working on creating separate patch files.
