### ISSUE TITLE
Please also give vaimo/composer-patches a shout out in the readme

### ISSUE THREAD

**Issue by peterjaap** [EmicoEcommerce/Magento-APSB22-48-Security-Patches#7]
This is a much better alternative to the cweagans one; https://github.com/vaimo/composer-patches

**Comment by stijnbernards** [comment]
Hi @peterjaap ,

Thanks I will, although I personally prefer cweagans due to higher usage statistics, but the vaimo composer patches package has better output regarding patching errors in my opinion.

**Comment by stijnbernards** [comment]
Done, added both as possible patching packages 👍
